### ISSUE TITLE
[1.7.10]Spamming NPCs

### ISSUE THREAD

**Issue by keenerb** [Millenaire/Millenaire#7]
Yes, I am aware that this is a 1.7.10 bug, but at this point in time 1.7.10 is about as ancient as 1.8; I hope you can revisit your 1.7.10 ban, especially since it's open source now.

**Please describe the issue you are having is as much detail as possible:**
Video of issue:
https://www.youtube.com/watch?v=q6-OpjrXKyw

When a town unloads and is subsequently reloaded, NPCs get stuck in some sort of loop.

**Describe how to be able to reproduce this bug:**

Visit a town.  Walk a good distance away from the town.  Return to the town.  Most (but usually not all) NPCs are broken in that they cause massive lag, they are unable to pathfind, their health bars flicker constantly, and they can only be interacted with if you spam right-click.  I don't know what's going on; are NPCs loaded differently when chunks are reloaded in this way?  Are they losing their target coordinates for pathfinding?  Are they stuck in some sort of reload loop?

**Further details:**
- Mod Version:
6.0.1

- Other Mod Versions (Seperated By Commas): 
Tested with and without other mods.  Issue occurs in both cases.

- Forge Version: 
1.7.10 1448 and 1614

**Comment by FireController1847** [comment]
We don't continue 1.7.10 because it's old, we discontinued it because of the differences in the code. The Forge API changed DRASTICALLY from 1.7.10 to 1.8.9, and this is why most mods did not update or were discontinued; because so much changed. We would love to continue coding 1.7.10, but due to the differences (and the fact it'd slow down 1.8.9 development), we don't.
